### ISSUE TITLE
NSFW commands throw error

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#105]
```
(node:722) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channel' of undefined
    at Object.execute (/Users/jasper/Desktop/Coding/Heptagram/commands/nsfw/ass.js:11:17)
    at module.exports (/Users/jasper/Desktop/Coding/Heptagram/events/client/message.js:12:34)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (/Users/jasper/Desktop/Coding/Heptagram/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
```
Commit on the staged branch.

**Comment by thinkverse** [comment]
Code causing the error.

https://github.com/Heptagram-Bot/Heptagram/blob/cdb2d1249ab6f282509acffe05cfb3da840c65de/commands/nsfw/ass.js#L11

Most likely done because the arguments aren't being destructured from the incoming object, they're being handled like arguments. Should destructure them from the object `({ client, message, args })`

https://github.com/Heptagram-Bot/Heptagram/blob/cdb2d1249ab6f282509acffe05cfb3da840c65de/commands/nsfw/ass.js#L9

**Comment by j-dogcoder** [comment]
I will try that. Thanks @thinkverse

**Comment by j-dogcoder** [comment]
Now it is throwing 
```
(node:4249) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.image.url: Could not interpret "{}" as string.
```
@thinkverse

**Comment by thinkverse** [comment]
Looking at the documentation for [akaneko](https://www.npmjs.com/package/akaneko) it seems the functions are asynchronous and need to be handled with either `await` or `then`. Since that isn't the case you're passing the  `Promise` to the embed, console the output and see what you get back. Their documentation also has an example for `discord.js` in it.

**Comment by j-dogcoder** [comment]
Works! Thanks for the help @thinkverse!
